title: "Ali Karimi"
author: "Ali"
description: "University of Naples Federico II"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true         # show article excerpts on the home page
show_frame: true            # adds a gray frame to the site
show_sidebar: false         # show a sidebar instead of the usual header
minimal: true               # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "/CV.pdf", title: "CV", icon: home}
  - {url: "https://www.apper-srl.it/", title: "My Lab"}
  - {file: "/Publications", title: "Publications"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:ali.karimi@unina.it"}
  - {title: Github, icon: github, url: "https://github.com/karimialii"}
  - {title: LinkedIn, icon: linkedin, url: "www.linkedin.com/in/alikarimiii"}
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
